rust:
  req1:
    method: GET
    url: https://www.rust-lang.org/ 
    headers:
      user-agent: Aloha
    params:
      hello: world
  req2:
    method: GET
    url: https://www.rust-lang.org/
    params: {}
  resp:
    skip_headers:
      - set-cookie
      - date
      - via
      - x-amz-cf-id
todo:
  req1:
    method: GET
    url: https://jsonplaceholder.typicode.com/todos/1 
    params:
      a: 100 
  req2:
    method: GET
    url: https://jsonplaceholder.typicode.com/todos/2 
    params:
      b: 200 
  resp:
    skip_headers:
      - content-length
      - report-to
      - reporting-endpoints
      # - date
      - x-ratelimit-remaining
      - cf-ray
      - server-timing
    skip_body:
      - id
todo2:
  req1:
    method: GET
    url: https://jsonplaceholder.typicode.com/todos/1
  req2:
    method: GET
    url: https://jsonplaceholder.typicode.com/todos/2
  resp:
    skip_headers:
    - date
    - content-length
    - report-to
    - reporting-endpoints
    - x-ratelimit-limit
    - x-ratelimit-remaining
    - x-ratelimit-reset
    - cf-cache-status
    - cf-ray
    - alt-svc